name: gestione_immagini
description: Progetto di ingegneria del software.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc: ^8.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_localizations:
    sdk: flutter
  flutter_services_binding: ^0.1.0
  intl: ^0.17.0
  local_storage_imgs_api:
    path: packages/local_storage_imgs_api
  img_api:
    path: packages/img_api
  imgs_repository:
    path: packages/imgs_repository

dev_dependencies:
  bloc_test: ^9.0.1
  flutter_test:
    sdk: flutter
  mockingjay: ^0.2.0
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true

