name: imgs_repository
description: A repository that handles img related requests.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  img_api:
    path: ../img_api
  selection_api:
    path: ../selection_api

dev_dependencies:
  mocktail: ^0.2.0
  test: ^1.17.0
  very_good_analysis: ^2.4.0